name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        go:
          - '1.21'
          - '1.22'
          - '1.23'
          - '1.24'

    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Go build wait
        run: go build ./wait/*.go

      - name: Go build exponential
        run: go build ./exponential/*.go
